export const DEFAULT_BOSSES = [
  {
    name: "Rusty Iron Knight",
    story:
      "A once-noble knight whose armor has rusted from years of neglect. Now he seeks worthy opponents to regain his former glory.",
    weakness: "Push-ups",
    health: 100,
    weaknessMultiplier: 2,
    challenge: [
      { exercise: "Push-ups", reps: 10 },
      { exercise: "Squats", reps: 15 },
      { exercise: "Plank", reps: 30 },
    ],
  },
  {
    name: "Shadow Monk",
    story:
      "A mysterious monk who has mastered the art of shadow combat. He tests warriors through trials of endurance.",
    weakness: "Plank",
    health: 150,
    weaknessMultiplier: 2.2,
    challenge: [
      { exercise: "Plank", reps: 45 },
      { exercise: "Push-ups", reps: 15 },
      { exercise: "Crunches", reps: 20 },
    ],
  },
  {
    name: "Mountain Titan",
    story:
      "A colossal being of stone and earth who challenges those who dare to scale his peaks.",
    weakness: "Squats",
    health: 200,
    weaknessMultiplier: 2.3,
    challenge: [
      { exercise: "Squats", reps: 25 },
      { exercise: "Lunges", reps: 20 },
      { exercise: "Crunches", reps: 30 },
    ],
  },
  {
    name: "Dragon Arms Commander",
    story:
      "A legendary warrior whose arms have been blessed with dragon's strength. He seeks those worthy of his training.",
    weakness: "Bicep Curls",
    health: 250,
    weaknessMultiplier: 2.4,
    challenge: [
      { exercise: "Bicep Curls", reps: 20 },
      { exercise: "Tricep Pushdowns", reps: 20 },
      { exercise: "Push-ups", reps: 25 },
    ],
  },
  {
    name: "Core Sentinel",
    story:
      "An ancient guardian whose power flows from his unbreakable core. He tests warriors' resilience.",
    weakness: "Crunches",
    health: 300,
    weaknessMultiplier: 2.5,
    challenge: [
      { exercise: "Crunches", reps: 40 },
      { exercise: "Plank", reps: 60 },
      { exercise: "Push-ups", reps: 30 },
    ],
  },
  {
    name: "Thunder Thighs Champion",
    story:
      "A warrior whose legendary leg strength can shake the earth. She challenges others to match her power.",
    weakness: "Deadlifts",
    health: 350,
    weaknessMultiplier: 2.6,
    challenge: [
      { exercise: "Deadlifts", reps: 15 },
      { exercise: "Squats", reps: 35 },
      { exercise: "Lunges", reps: 30 },
    ],
  },
  {
    name: "Wing Master Phoenix",
    story:
      "A mystical being who has mastered the art of aerial combat. He tests warriors' upper body strength.",
    weakness: "Pull-ups",
    health: 400,
    weaknessMultiplier: 2.7,
    challenge: [
      { exercise: "Pull-ups", reps: 10 },
      { exercise: "Push-ups", reps: 40 },
      { exercise: "Shoulder Press", reps: 20 },
    ],
  },
  {
    name: "Iron Trinity",
    story:
      "Three ancient spirits bound in one form, demanding mastery of multiple disciplines.",
    weakness: "Shoulder Press",
    health: 450,
    weaknessMultiplier: 2.8,
    challenge: [
      { exercise: "Shoulder Press", reps: 25 },
      { exercise: "Pull-ups", reps: 12 },
      { exercise: "Push-ups", reps: 45 },
    ],
  },
  {
    name: "Eternal Endurance",
    story:
      "A timeless being who has never tired in centuries of existence. She challenges mortals to push their limits.",
    weakness: "Tricep Pushdowns",
    health: 500,
    weaknessMultiplier: 2.9,
    challenge: [
      { exercise: "Tricep Pushdowns", reps: 30 },
      { exercise: "Plank", reps: 90 },
      { exercise: "Push-ups", reps: 50 },
    ],
  },
  {
    name: "Balance Keeper",
    story:
      "A mysterious entity who maintains the equilibrium of strength. Tests warriors' complete mastery.",
    weakness: "Lunges",
    health: 550,
    weaknessMultiplier: 3.0,
    challenge: [
      { exercise: "Lunges", reps: 40 },
      { exercise: "Squats", reps: 45 },
      { exercise: "Deadlifts", reps: 20 },
    ],
  },
  {
    name: "Titan of Iron Valley",
    story:
      "The legendary ruler of Iron Valley, whose strength has become mythical. Few dare to challenge him.",
    weakness: "Deadlifts",
    health: 600,
    weaknessMultiplier: 3.1,
    challenge: [
      { exercise: "Deadlifts", reps: 25 },
      { exercise: "Squats", reps: 50 },
      { exercise: "Pull-ups", reps: 15 },
    ],
  },
  {
    name: "Strength Spectrum",
    story:
      "A being composed of pure energy who has mastered every form of strength training.",
    weakness: "Push-ups",
    health: 650,
    weaknessMultiplier: 3.2,
    challenge: [
      { exercise: "Push-ups", reps: 60 },
      { exercise: "Pull-ups", reps: 20 },
      { exercise: "Shoulder Press", reps: 30 },
    ],
  },
  {
    name: "Core Nexus",
    story:
      "The embodiment of core strength itself, challenging warriors to reach their absolute limits.",
    weakness: "Plank",
    health: 700,
    weaknessMultiplier: 3.3,
    challenge: [
      { exercise: "Plank", reps: 120 },
      { exercise: "Crunches", reps: 60 },
      { exercise: "Push-ups", reps: 70 },
    ],
  },
  {
    name: "Primal Force",
    story:
      "An ancient being who has existed since the dawn of strength itself. The ultimate test of power.",
    weakness: "Squats",
    health: 800,
    weaknessMultiplier: 3.4,
    challenge: [
      { exercise: "Squats", reps: 60 },
      { exercise: "Deadlifts", reps: 30 },
      { exercise: "Pull-ups", reps: 25 },
    ],
  },
  {
    name: "Omega Champion",
    story:
      "The final guardian of strength, whose power is said to rival the gods themselves.",
    weakness: "Pull-ups",
    health: 1000,
    weaknessMultiplier: 3.5,
    challenge: [
      { exercise: "Pull-ups", reps: 30 },
      { exercise: "Push-ups", reps: 100 },
      { exercise: "Squats", reps: 75 },
    ],
  },
  {
    name: "Frostbite Warlord",
    story:
      "A warrior encased in ice, whose chilling presence freezes even the strongest of wills.",
    weakness: "Burpees",
    health: 850,
    weaknessMultiplier: 3.6,
    challenge: [
      { exercise: "Burpees", reps: 20 },
      { exercise: "Push-ups", reps: 80 },
      { exercise: "Plank", reps: 90 },
    ],
  },
  {
    name: "Inferno Berserker",
    story:
      "A fiery warrior whose rage burns hotter than the sun. Only the strongest can withstand his heat.",
    weakness: "Mountain Climbers",
    health: 900,
    weaknessMultiplier: 3.7,
    challenge: [
      { exercise: "Mountain Climbers", reps: 50 },
      { exercise: "Push-ups", reps: 90 },
      { exercise: "Squats", reps: 70 },
    ],
  },
  {
    name: "Abyssal Colossus",
    story:
      "A towering figure from the depths of the abyss, challenging warriors to face their darkest fears.",
    weakness: "Deadlifts",
    health: 950,
    weaknessMultiplier: 3.8,
    challenge: [
      { exercise: "Deadlifts", reps: 35 },
      { exercise: "Pull-ups", reps: 30 },
      { exercise: "Plank", reps: 120 },
    ],
  },
  {
    name: "Celestial Archer",
    story:
      "A divine archer whose arrows never miss. She tests warriors' agility and precision.",
    weakness: "Lunges",
    health: 1100,
    weaknessMultiplier: 3.9,
    challenge: [
      { exercise: "Lunges", reps: 50 },
      { exercise: "Push-ups", reps: 100 },
      { exercise: "Plank", reps: 150 },
    ],
  },
  {
    name: "Void Warden",
    story:
      "A guardian of the void, whose power is as infinite as the darkness itself.",
    weakness: "Pull-ups",
    health: 1200,
    weaknessMultiplier: 4.0,
    challenge: [
      { exercise: "Pull-ups", reps: 40 },
      { exercise: "Push-ups", reps: 120 },
      { exercise: "Squats", reps: 80 },
    ],
  },
  {
    name: "Stormcaller",
    story:
      "A master of the elements who commands the fury of the storm. Only the bravest can face his wrath.",
    weakness: "Burpees",
    health: 1300,
    weaknessMultiplier: 4.1,
    challenge: [
      { exercise: "Burpees", reps: 30 },
      { exercise: "Push-ups", reps: 130 },
      { exercise: "Plank", reps: 180 },
    ],
  },
  {
    name: "Eclipse Sentinel",
    story:
      "A being born during a solar eclipse, whose power waxes and wanes with the moon.",
    weakness: "Crunches",
    health: 1400,
    weaknessMultiplier: 4.2,
    challenge: [
      { exercise: "Crunches", reps: 80 },
      { exercise: "Push-ups", reps: 140 },
      { exercise: "Squats", reps: 90 },
    ],
  },
  {
    name: "Ironclad Behemoth",
    story:
      "A massive creature clad in impenetrable iron, challenging warriors to break through its defenses.",
    weakness: "Deadlifts",
    health: 1500,
    weaknessMultiplier: 4.3,
    challenge: [
      { exercise: "Deadlifts", reps: 40 },
      { exercise: "Pull-ups", reps: 50 },
      { exercise: "Plank", reps: 200 },
    ],
  },
  {
    name: "Blaze Phoenix",
    story:
      "A fiery phoenix reborn from ashes, testing warriors' endurance and willpower.",
    weakness: "Mountain Climbers",
    health: 1600,
    weaknessMultiplier: 4.4,
    challenge: [
      { exercise: "Mountain Climbers", reps: 60 },
      { exercise: "Push-ups", reps: 150 },
      { exercise: "Squats", reps: 100 },
    ],
  },
  {
    name: "Tidal Leviathan",
    story:
      "A sea monster whose waves can crush even the strongest of ships. Only the most resilient can survive.",
    weakness: "Burpees",
    health: 1700,
    weaknessMultiplier: 4.5,
    challenge: [
      { exercise: "Burpees", reps: 40 },
      { exercise: "Push-ups", reps: 160 },
      { exercise: "Plank", reps: 220 },
    ],
  },
  {
    name: "Solar Titan",
    story:
      "A titan who draws power from the sun, challenging warriors to match his radiant energy.",
    weakness: "Pull-ups",
    health: 1800,
    weaknessMultiplier: 4.6,
    challenge: [
      { exercise: "Pull-ups", reps: 60 },
      { exercise: "Push-ups", reps: 170 },
      { exercise: "Squats", reps: 110 },
    ],
  },
  {
    name: "Lunar Warden",
    story: "A guardian of the moon, whose calm demeanor hides immense power.",
    weakness: "Lunges",
    health: 1900,
    weaknessMultiplier: 4.7,
    challenge: [
      { exercise: "Lunges", reps: 60 },
      { exercise: "Push-ups", reps: 180 },
      { exercise: "Plank", reps: 240 },
    ],
  },
  {
    name: "Eternal Flame",
    story:
      "A being of pure fire, whose flames never extinguish. Only the strongest can withstand its heat.",
    weakness: "Burpees",
    health: 2000,
    weaknessMultiplier: 4.8,
    challenge: [
      { exercise: "Burpees", reps: 50 },
      { exercise: "Push-ups", reps: 200 },
      { exercise: "Squats", reps: 120 },
    ],
  },
];

export const EQUIPMENT_CONFIG = {
  types: [
    "weapon",
    "armor",
    "shield",
    "helmet",
    "gauntlets",
    "boots",
    "amulet",
    "ring",
    "cloak",
    "belt",
    "bow",
    "crossbow",
    "staff",
    "wand",
    "dagger",
    "axe",
    "mace",
    "spear",
    "hammer",
    "scythe",
  ],
  rarities: [
    "Common",
    "Uncommon",
    "Rare",
    "Epic",
    "Legendary",
    "Mythic",
    "Divine",
    "Cursed",
    "Forgotten",
    "Ethereal",
  ],
  prefixes: [
    "Dragon's",
    "Knight's",
    "Warrior's",
    "Ancient",
    "Blessed",
    "Cursed",
    "Frozen",
    "Flaming",
    "Thundering",
    "Venomous",
    "Radiant",
    "Shadow",
    "Celestial",
    "Infernal",
    "Abyssal",
    "Primal",
    "Eternal",
    "Spectral",
    "Void",
    "Arcane",
  ],
  suffixes: [
    "of Power",
    "of Vitality",
    "of the Champion",
    "of Glory",
    "of the Titan",
    "of the Phoenix",
    "of the Wolf",
    "of the Bear",
    "of the Eagle",
    "of the Serpent",
    "of the Stars",
    "of the Moon",
    "of the Sun",
    "of the Storm",
    "of the Abyss",
    "of the Void",
    "of the Ancients",
    "of the Elements",
    "of the Forgotten",
    "of the Eternal",
  ],
  materials: [
    "Iron",
    "Steel",
    "Silver",
    "Gold",
    "Platinum",
    "Mithril",
    "Adamantium",
    "Obsidian",
    "Crystal",
    "Bone",
    "Wood",
    "Leather",
    "Scale",
    "Chainmail",
    "Plate",
    "Silk",
    "Linen",
    "Wool",
    "Runic",
    "Ethereal",
  ],
  effects: [
    "Fire Damage",
    "Ice Damage",
    "Lightning Damage",
    "Poison Damage",
    "Holy Damage",
    "Dark Damage",
    "Life Steal",
    "Mana Steal",
    "Increased Strength",
    "Increased Dexterity",
    "Increased Intelligence",
    "Increased Vitality",
    "Increased Luck",
    "Critical Strike Chance",
    "Critical Strike Damage",
    "Armor Penetration",
    "Magic Penetration",
    "Damage Reflection",
    "Damage Reduction",
    "Health Regeneration",
  ],
  origins: [
    "Forged in the Heart of a Volcano",
    "Crafted by Elven Artisans",
    "Blessed by the Gods",
    "Cursed by a Dark Sorcerer",
    "Forged in the Depths of the Abyss",
    "Crafted by Dwarven Masters",
    "Infused with Dragon's Breath",
    "Bathed in Celestial Light",
    "Tempered in the Frozen Wastes",
    "Quenched in the Blood of Titans",
    "Forged in the Fires of War",
    "Crafted by Ancient Civilizations",
    "Infused with the Power of the Stars",
    "Blessed by the Moon Goddess",
    "Cursed by the Sun God",
    "Forged in the Shadow Realm",
    "Crafted by the Last of the Giants",
    "Infused with the Essence of the Void",
    "Blessed by the Spirits of Nature",
    "Cursed by the Undead King",
  ],
  rarityMultipliers: {
    Common: 1,
    Uncommon: 1.2,
    Rare: 1.5,
    Epic: 2,
    Legendary: 3,
    Mythic: 4,
    Divine: 5,
    Cursed: 0.8,
    Forgotten: 0.5,
    Ethereal: 2.5,
  },
};
